# This is a shared Makefile for building menuet apps. 
# To use it, create a Makefile in your applications directory, set the name of the app, and include this file. 
# For example:
#
#   APP=Hello World
#   include $(GOPATH)/src/github.com/caseymrm/menuet/menuet.mk
#
# Optional features:
# 
# To set your CFBundleIdentifier, set IDENTIFIER:
#   IDENTIFIER=whyawake.caseymrm.github.com
#
# To monitor other directories for source changes, set LIBDIRS:
#   LIBDIR= ../go-pmset ../go-caffeinate
#
# To sign your app, set IDENTITY:
#   IDENTITY=Developer ID Application: Hello World LLC (AP2AFA8XAX)
#
# To release your app, `make release` builds + zips the bundle and uploads
# it to GitHub via the gh CLI (install with `brew install gh`; authenticate
# once with `gh auth login`). The zip asset is what menuet's AutoUpdate
# auto-updater downloads.

ifndef APP
  $(error APP variable must be defined, e.g. APP=Hello World)
endif

space :=
space +=
ESCAPED_APP = $(subst $(space),\$(space),$(APP))
EXECUTABLE := $(shell echo $(subst $(space),,$(APP)) | tr '[:upper:]' '[:lower:]')
BINARY = $(ESCAPED_APP).app/Contents/MacOS/$(EXECUTABLE)
PLIST = $(ESCAPED_APP).app/Contents/Info.plist

run: $(BINARY) $(PLIST)
	./$(BINARY)

SOURCEDIRS = $(abspath $(dir $(MAKEFILE_LIST)))
SOURCES := $(shell find $(SOURCEDIRS) $(LIBDIRS) -name '*.go' -o -name '*.m' -o -name '*.h' -o -name '*.c' -o -name '*.mk' -o -name Makefile)

$(BINARY): $(SOURCES)
	go build -o $(BINARY)

ZIPFILE = $(ESCAPED_APP).zip

$(ZIPFILE): sign $(BINARY) $(PLIST)
	zip -r $(ZIPFILE) $(ESCAPED_APP).app

clean:
	rm -f $(BINARY) $(PLIST) $(ZIPFILE)

.PHONY: zip
zip: $(ZIPFILE)

.PHONY: releases
releases:
	@gh release list

.PHONY: release
release: $(ZIPFILE)
	@LATEST=$$(gh release view --json tagName -q .tagName 2>/dev/null || echo "(none)"); \
	echo "Latest release: $$LATEST"; \
	read -p "New tag (e.g. v1.0.0): " TAG; \
	read -p "Release notes (one line, or empty for autogenerated): " NOTES; \
	if [ -z "$$NOTES" ]; then \
		gh release create "$$TAG" "$(ZIPFILE)" --title "$$TAG" --generate-notes; \
	else \
		gh release create "$$TAG" "$(ZIPFILE)" --title "$$TAG" --notes "$$NOTES"; \
	fi

IDENTIFIER ?= $(EXECUTABLE).menuet.caseymrm.github.com

$(PLIST):
	echo "Generating plist..."
	@echo '<?xml version="1.0" encoding="UTF-8"?>' > $(PLIST)
	@echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> $(PLIST)
	@echo '<plist version="1.0">' >> $(PLIST)
	@echo '<dict>' >> $(PLIST)
	@echo '  <key>CFBundleExecutable</key>' >> $(PLIST)
	@echo '  <string>$(EXECUTABLE)</string>' >> $(PLIST)
	@echo '  <key>CFBundleIconFile</key>' >> $(PLIST)
	@echo '  <string>icon</string>' >> $(PLIST)
	@echo '  <key>CFBundleGetInfoString</key>' >> $(PLIST)
	@echo '  <string>$(APP)</string>' >> $(PLIST)
	@echo '  <key>CFBundleIdentifier</key>' >> $(PLIST)
	@echo '  <string>$(IDENTIFIER)</string>' >> $(PLIST)
	@echo '  <key>CFBundleName</key>' >> $(PLIST)
	@echo '  <string>$(APP)</string>' >> $(PLIST)
	@echo '  <key>CFBundleShortVersionString</key>' >> $(PLIST)
	@echo '  <string>0.1</string>' >> $(PLIST)
	@echo '  <key>CFBundleInfoDictionaryVersion</key>' >> $(PLIST)
	@echo '  <string>6.0</string>' >> $(PLIST)
	@echo '  <key>CFBundlePackageType</key>' >> $(PLIST)
	@echo '  <string>APPL</string>' >> $(PLIST)
	@echo '  <key>IFMajorVersion</key>' >> $(PLIST)
	@echo '  <integer>0</integer>' >> $(PLIST)
	@echo '  <key>IFMinorVersion</key>' >> $(PLIST)
	@echo '  <integer>1</integer>' >> $(PLIST)
	@echo '  <key>NSHighResolutionCapable</key><true/>' >> $(PLIST)
	@echo '  <key>NSSupportsAutomaticGraphicsSwitching</key><true/>' >> $(PLIST)
	@echo '</dict>' >> $(PLIST)
	@echo '</plist>' >> $(PLIST)

.PHONY: sign
sign: $(BINARY) $(PLIST)
	codesign -f -s "$(IDENTITY)" $(ESCAPED_APP).app --deep

# `make web-preview` writes menuet-demo.json — a JSON snapshot of the
# current MenuState and resolved menu items — by re-running the binary
# in snapshot mode. The snapshot is safe to commit to your repo;
# menuet.app fetches it to render a faithful HTML mockup of your menu.
#
# Default delay is 2s; override with MENUET_SNAPSHOT_DELAY=5s when your
# app fetches data on startup and you want the menu to reflect real
# values in the demo.
.PHONY: web-preview
web-preview: $(BINARY) $(PLIST)
	MENUET_SNAPSHOT_PATH=menuet-demo.json ./$(BINARY)
	@echo "Wrote menuet-demo.json"
