# This is a shared Makefile for building menuet apps. 
# To use it, create a Makefile in your applications directory, set the name of the app, and include this file. 
# For example:
#
#   APP=Hello World
#   include $(GOPATH)/src/github.com/caseymrm/menuet/menuet.mk
#
# Optional features:
# 
# To set your CFBundleIdentifier, set IDENTIFIER:
#   IDENTIFIER=whyawake.caseymrm.github.com
#
# To monitor other directories for source changes, set LIBDIRS:
#   LIBDIR= ../go-pmset ../go-caffeinate
#
# To set the app icon, drop an icon.icns next to your Makefile; it is copied
# into the bundle automatically. Override the path with ICON:
#   ICON=assets/myicon.icns
# With no icon.icns present, a fallback icon (a colored rounded square with
# the app's first letter) is generated from the app name. Its color is derived
# from the name; override it with ICON_COLOR:
#   ICON_COLOR=#4A90D9
# The fallback lives only inside the .app, so `make clean` refreshes it if you
# change the name or color.
#
# To sign your app, set IDENTITY:
#   IDENTITY=Developer ID Application: Hello World LLC (AP2AFA8XAX)
#
# With a real (non ad-hoc) IDENTITY, `make sign` applies the hardened
# runtime and a secure timestamp, and `make notarize` submits the zip to
# Apple's notary service and staples the ticket — see the notarize target
# below for the one-time credential setup.
#
# To release your app, `make release` builds + zips the bundle and uploads
# it to GitHub via the gh CLI (install with `brew install gh`; authenticate
# once with `gh auth login`). The zip asset is what menuet's AutoUpdate
# auto-updater downloads.

ifndef APP
  $(error APP variable must be defined, e.g. APP=Hello World)
endif

space :=
space +=
ESCAPED_APP = $(subst $(space),\$(space),$(APP))
EXECUTABLE := $(shell echo $(subst $(space),,$(APP)) | tr '[:upper:]' '[:lower:]')
BINARY = $(ESCAPED_APP).app/Contents/MacOS/$(EXECUTABLE)
PLIST = $(ESCAPED_APP).app/Contents/Info.plist
ICON ?= $(wildcard icon.icns)
ICNS = $(ESCAPED_APP).app/Contents/Resources/icon.icns

run: $(BINARY) $(PLIST) $(ICNS)
	./$(BINARY)

SOURCEDIRS = $(abspath $(dir $(MAKEFILE_LIST)))
SOURCES := $(shell find $(SOURCEDIRS) $(LIBDIRS) -name '*.go' -o -name '*.m' -o -name '*.h' -o -name '*.c' -o -name '*.mk' -o -name Makefile)

$(BINARY): $(SOURCES)
	go build -o $(BINARY)

ZIPFILE = $(ESCAPED_APP).zip

# ditto (not zip -r) preserves symlinks, extended attributes, and the
# stapled notarization ticket — Apple's documented archiver for app zips.
# The bundle icon: copy a supplied icon.icns, or generate a fallback from the
# app name. The app name can contain spaces, so quote the paths in the recipe.
$(ICNS): $(ICON)
	mkdir -p "$(APP).app/Contents/Resources"
ifeq ($(ICON),)
	go run github.com/caseymrm/menuet/v2/cmd/appicon -name "$(APP)" $(if $(ICON_COLOR),-color "$(ICON_COLOR)") -o "$(APP).app/Contents/Resources/icon.icns"
else
	cp "$(ICON)" "$(APP).app/Contents/Resources/icon.icns"
endif

$(ZIPFILE): sign $(BINARY) $(PLIST) $(ICNS)
	ditto -c -k --keepParent $(ESCAPED_APP).app $(ZIPFILE)

clean:
	rm -f $(BINARY) $(PLIST) $(ZIPFILE) $(ICNS)

.PHONY: zip
zip: $(ZIPFILE)

.PHONY: releases
releases:
	@gh release list

.PHONY: release
release: $(ZIPFILE)
	@LATEST=$$(gh release view --json tagName -q .tagName 2>/dev/null || echo "(none)"); \
	echo "Latest release: $$LATEST"; \
	read -p "New tag (e.g. v1.0.0): " TAG; \
	read -p "Release notes (one line, or empty for autogenerated): " NOTES; \
	if [ -z "$$NOTES" ]; then \
		gh release create "$$TAG" "$(ZIPFILE)" --title "$$TAG" --generate-notes; \
	else \
		gh release create "$$TAG" "$(ZIPFILE)" --title "$$TAG" --notes "$$NOTES"; \
	fi

IDENTIFIER ?= $(EXECUTABLE).menuet.caseymrm.github.com

$(PLIST):
	echo "Generating plist..."
	@echo '<?xml version="1.0" encoding="UTF-8"?>' > $(PLIST)
	@echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> $(PLIST)
	@echo '<plist version="1.0">' >> $(PLIST)
	@echo '<dict>' >> $(PLIST)
	@echo '  <key>CFBundleExecutable</key>' >> $(PLIST)
	@echo '  <string>$(EXECUTABLE)</string>' >> $(PLIST)
	@echo '  <key>CFBundleIconFile</key>' >> $(PLIST)
	@echo '  <string>icon</string>' >> $(PLIST)
	@echo '  <key>CFBundleGetInfoString</key>' >> $(PLIST)
	@echo '  <string>$(APP)</string>' >> $(PLIST)
	@echo '  <key>CFBundleIdentifier</key>' >> $(PLIST)
	@echo '  <string>$(IDENTIFIER)</string>' >> $(PLIST)
	@echo '  <key>CFBundleName</key>' >> $(PLIST)
	@echo '  <string>$(APP)</string>' >> $(PLIST)
	@echo '  <key>CFBundleShortVersionString</key>' >> $(PLIST)
	@echo '  <string>0.1</string>' >> $(PLIST)
	@echo '  <key>CFBundleInfoDictionaryVersion</key>' >> $(PLIST)
	@echo '  <string>6.0</string>' >> $(PLIST)
	@echo '  <key>CFBundlePackageType</key>' >> $(PLIST)
	@echo '  <string>APPL</string>' >> $(PLIST)
	@echo '  <key>IFMajorVersion</key>' >> $(PLIST)
	@echo '  <integer>0</integer>' >> $(PLIST)
	@echo '  <key>IFMinorVersion</key>' >> $(PLIST)
	@echo '  <integer>1</integer>' >> $(PLIST)
	@echo '  <key>NSHighResolutionCapable</key><true/>' >> $(PLIST)
	@echo '  <key>NSSupportsAutomaticGraphicsSwitching</key><true/>' >> $(PLIST)
	@echo '</dict>' >> $(PLIST)
	@echo '</plist>' >> $(PLIST)

# Hardened runtime + secure timestamp are required for notarization, but
# both need a real signing certificate — ad-hoc signatures ("-", the
# default in some apps) can't produce a timestamp, so only add the flags
# for a real identity.
ifeq ($(IDENTITY),-)
SIGNFLAGS =
else
SIGNFLAGS = --options runtime --timestamp
endif

.PHONY: sign
sign: $(BINARY) $(PLIST) $(ICNS)
	codesign -f $(SIGNFLAGS) -s "$(IDENTITY)" $(ESCAPED_APP).app --deep

# Notarize the signed zip, staple the ticket to the .app, and re-zip so
# the release artifact carries the ticket (Gatekeeper then clears the app
# even offline). One-time setup for the keychain profile:
#   xcrun notarytool store-credentials AC_NOTARY
# (prompts for Apple ID, team ID, and an app-specific password from
# appleid.apple.com). Override the profile name with NOTARY_PROFILE.
NOTARY_PROFILE ?= AC_NOTARY

.PHONY: notarize
notarize: $(ZIPFILE)
	xcrun notarytool submit $(ZIPFILE) --keychain-profile $(NOTARY_PROFILE) --wait
	xcrun stapler staple $(ESCAPED_APP).app
	rm -f $(ZIPFILE)
	ditto -c -k --keepParent $(ESCAPED_APP).app $(ZIPFILE)

# `make web-preview` writes menuet-demo.json — a JSON snapshot of the
# current MenuState and resolved menu items — by re-running the binary
# in snapshot mode. The snapshot is safe to commit to your repo;
# menuet.app fetches it to render a faithful HTML mockup of your menu.
#
# Default delay is 2s; override with MENUET_SNAPSHOT_DELAY=5s when your
# app fetches data on startup and you want the menu to reflect real
# values in the demo.
.PHONY: web-preview
web-preview: $(BINARY) $(PLIST)
	MENUET_SNAPSHOT_PATH=menuet-demo.json ./$(BINARY)
	@echo "Wrote menuet-demo.json"
